services:

  product-service:
    build:
      context: product-service
      dockerfile: Dockerfile
    ports:
      - "1234:8080"

  invoice-service:
    build:
      context: invoice-service
      dockerfile: Dockerfile
    ports:
      - "1235:8080"

  kong-database:
    # container_name: kong-database
    image: postgres:14.4-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kongpass
      - POSTGRES_DB=kong

  kong-migration:
    image: kong:3.2.2-alpine
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpass
      KONG_PASSWORD: test
    depends_on:
      - kong-database
    restart: on-failure
    entrypoint:
      - "kong"
      - "migrations"
      - "bootstrap"

  kong-gateway:
    image: kong:3.2.2-alpine
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-database
      - kong-migration
    restart: on-failure
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
